### ISSUE TITLE
CONTRIBUTING.md broken at project-awesome

### ISSUE THREAD

**Issue by andrew-appel** [coq-community/awesome-coq#27]
At https://project-awesome.org/coq-community/awesome-coq it says,
`Contributions welcome! Read the contribution guidelines first`
which is a link to 
https://project-awesome.org/coq-community/CONTRIBUTING.md
which is a broken link.

**Comment by Zimmi48** [comment]
Good catch! It looks like only absolute links can be used in `README.md` if they end up being duplicated on this website.

**Comment by palmskog** [comment]
I had no idea the repo was included in this way on project-awesome.org, thanks. Should be fixed now (or eventually, when they fetch the changes)
