### ISSUE TITLE
Adding an external URL such as `project-awesome.org` in the repo description?

### ISSUE THREAD

**Issue by erikmd** [coq-community/awesome-coq#29]
Hi,

I was thinking about suggesting some continuous deployment of the `awesome-coq` repository,
however I noticed there are several standard websites that already do this! e.g.:

1. https://project-awesome.org/coq-community/awesome-coq
2. https://github.com/sindresorhus/awesome#related

@anton-trunov @palmskog would you agree to add the link 1. above somewhere in the GitHub repo? (say, in the README and/or in the repo description URL)

**Comment by anton-trunov** [comment]
@erikmd Great idea! Btw, the first link shows me lots of ads -- I'm wondering if there is an option without ads?

**Comment by palmskog** [comment]
@erikmd I added the `project-awesome.org` link in the "About" part of the repo (i.e., not in the repo content). Is that what you had in mind. I don't think we want to have any link like that in the repo content.

**Comment by erikmd** [comment]
Closed by #31
