### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by anton-trunov** [coq-community/awesome-coq#33]
The current classification is based on type of content, scope or implementation details (books / libraries / plugins / etc). I think it would be nice to have some tags, like keywords in scientific publications, attached to each entry. For instance, something like `machine-learning`, `proof-automation` for the Tactician tool.

**Comment by palmskog** [comment]
@anton-trunov my view is that this repo should follow other similar Awesome list repos as closely as possible format-wise, which would preclude tags. To me, tags could be added if what we were doing was a *database* of Coq projects regardless of noteworthiness - but this is quite far from what Awesome lists are about.

**Comment by anton-trunov** [comment]
@palmskog Fair enough. I think it's worth it to add this to the contributing guide and close this issue.

**Comment by palmskog** [comment]
@anton-trunov we already say that the format looks like this:
```
- [Name](URL) - Description.
```
I don't see how this would give any room for tags.
