### ISSUE TITLE
Since I find Bedrock to be awesome, I am not sure about its current status

### ISSUE THREAD

**Issue by vonavi** [coq-community/awesome-coq#34]
Hello everyone!

There is the Bedrock library (the original URL https://plv.csail.mit.edu/bedrock, project on GitHub https://github.com/mit-plv/bedrock) for mostly automated verification of higher-order programs with higher-order separation logic. I found it very useful from the pedagogical point of view, however, it looks unmaintained now.

I've found that examples inside Bedrock work with the [depl brach](https://github.com/mit-plv/bedrock/tree/depl), OCaml 4.01.0, and Coq 8.4pl2. Below is a simple example of library usage:

```coq
Require Export String.
Require Import Bedrock.Word Bedrock.IL Bedrock.Programming.

Open Scope string_scope.

Definition xIncS := SPEC("x") reserving 1
  PRE[V] [| V "x" <= $10 |]
  POST[R] [| R = $10 |].

Definition xIncM := bmodule "x_inc" {{
  bfunction "x_inc"("x") [xIncS]
    "x" <- 0;;
    [ PRE[V] [| V "x" <= $10 |]%word
      POST[R] [| R = $10 |]%word ]
    While ("x" < 10) {
      "x" <- "x" + 1
    };;
    Return "x"
  end
}}.

Theorem xIncOk : moduleOk xIncM.
Proof.
  vcgen; sep_auto.
```

The contents of `_CoqProject`:
```
-R src Bedrock
-I platform
```

Best regards,
Vladimir.

**Comment by Zimmi48** [comment]
Are you aware of bedrock2? https://github.com/mit-plv/bedrock2
AFAIU, this is a reimplementation from scratch, and it is actively maintained.

**Comment by palmskog** [comment]
The original Bedrock library is not an actively maintained project and has been unmaintained for a long time, so it's not compatible with our contributing guidelines. If anyone wants to propose Bedrock2 as an addition to the list, please do so in a new pull request, and be sure to give specific motivation for that addition.
